using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;

namespace OpenLEAudio;

/// <summary>Runtime language packs with stable keys and an English fallback.</summary>
public static class Loc
{
    private sealed record Pack(string Code, string Name, Dictionary<string, string> Strings);

    private static readonly Dictionary<string, string> En = new()
    {
        ["section.recovery"] = "Audio recovery",
        ["section.recovery.sub"] = "Restore sound while keeping the Bluetooth connection",
        ["setting.audio_recovery_enabled"] = "Automatically recover audio",
        ["setting.audio_recovery_interval_s"] = "Pause between audio recovery attempts (seconds)",
        ["setting.audio_recovery_window_min"] = "Audio recovery time limit (minutes)",
        ["desc.audio_recovery_enabled"] = "Rebuild failed audio channels without deliberately disconnecting Bluetooth. Ordinary missing packets do not require rebuilding. Independent of full Bluetooth reconnection.",
        ["desc.audio_recovery_interval_s"] = "Pause after an audio failure or unsuccessful recovery. Channel setup adds time. Changes also apply while waiting.",
        ["desc.audio_recovery_window_min"] = "0 keeps trying until you stop or the Bluetooth link ends. Recovery waits while the peer is using another source. A finite limit stops audio recovery without deliberately disconnecting Bluetooth.",
        ["setting.acl_phy"] = "Control connection PHY preference",
        ["choice.acl_auto"] = "Automatic (1M or 2M)",
        ["desc.acl_phy"] = "Separate from the audio CIS PHY. Automatic lets the controller negotiate 1M or 2M; it is not a signal-based switching algorithm. A preference is not a guarantee. The log reports the negotiated result.",
        ["log.audio_recovery"] = "Audio interrupted: waiting to rebuild audio channels; Bluetooth connection retained.",
        ["log.audio_recovery_stopped"] = "Automatic audio recovery stopped by settings or time limit. Reconnect manually to resume.",

        ["device.info_custom"] = "Custom: selected value | application range (headset limits below)",
        ["device.info_qos_note"] = "PAC rows describe allowed codec combinations. QoS limits above belong only to the stated last negotiated codec and PHY. RTN and PHY preferences are not complete support ranges. Unknown combinations require device and controller negotiation.",
        ["radio.explanation"] = "Read-only standard HCI telemetry. Absolute connection TX power is controlled by the controller/firmware; there is no universal HCI slider. Adapter power range is not the current connection power. An unavailable reading is not 0 dBm.",
        ["radio.unknown"] = "unavailable",
        ["radio.tx"] = "Local TX",
        ["radio.link_max"] = "Connection maximum",
        ["radio.range"] = "Adapter range",
        ["preflight.invalid"] = "Configuration rejected before reconnect",

        ["device.star_hint"] = "Star: allow connections without confirmation, including reconnection",
        ["device.confirm_title"] = "Allow connection?",
        ["device.confirm_body"] = "This device is not starred. Confirm this connection; pairing will run if needed.",
        ["device.cancel"] = "Cancel",
        ["device.info_title"] = "Device capabilities",
        ["device.info_current"] = "Confirmed stream configuration",
        ["device.info_supported"] = "LC3 capabilities reported by the device (one record per line)",
        ["device.info_help"] = "Choose Custom in Settings. Pick rate, frame duration and bytes from the same record; not every combination across records is supported. Bitrate (kb/s/channel) = bytes × 8 / frame (ms). Transport latency is a ceiling; presentation delay is limited by both ASEs after codec negotiation. Minimum latency is not guaranteed at every bitrate or radio condition.",

        ["nav.setup"] = "Setup", ["nav.devices"] = "Devices", ["nav.settings"] = "Settings", ["nav.language"] = "Language", ["nav.about"] = "About",
        ["devices.title"] = "Bluetooth & devices", ["status.starting"] = "Starting…",
        ["status.unavailable"] = "Unavailable", ["status.core_failed"] = "The audio service could not start",
        ["status.core_unavailable"] = "The audio service is unavailable",
        ["status.turning_on"] = "Turning on…", ["status.turning_off"] = "Turning off…",
        ["status.scanning"] = "Searching for devices…", ["status.off"] = "Off",
        ["status.adapter_off"] = "The adapter is off", ["status.none_found"] = "Nothing new nearby",
        ["status.scan_failed"] = "Search failed", ["devices.bluetooth"] = "Bluetooth",
        ["status.found"] = "Found: {0}",
        ["devices.scan_again"] = "Search again", ["devices.paired"] = "Paired devices",
        ["devices.found"] = "Discovered devices", ["devices.unpair"] = "Unpair",
        ["common.on"] = "On", ["common.off"] = "Off", ["common.saved"] = "saved",
        ["common.success"] = "Done", ["common.error"] = "Something went wrong",
        ["device.connecting"] = "Connecting…", ["device.connected_playing"] = "Connected, playing",
        ["device.connected"] = "Connected", ["device.paired"] = "Paired", ["device.playing"] = "Playing",
        ["device.disconnect"] = "Disconnect", ["device.connect"] = "Connect", ["device.pair"] = "Pair",
        ["log.title"] = "Activity", ["log.debug_on"] = "Debug on", ["log.debug_off"] = "Debug off",
        ["log.follow_on"] = "Following new entries", ["log.follow_off"] = "Following paused",
        ["log.down"] = "↓ Bottom", ["log.copy"] = "Copy all", ["log.copied"] = "Copied",
        ["log.clear"] = "Clear", ["log.debug_tip"] = "Detailed HCI/ACL/ISO packets; turning debug off clears the detailed log",
        ["log.down_tip"] = "Jump to the end and follow new entries again",
        ["log.debug_disabled"] = "Debug off. Packet-level detail stops; the console keeps its history, trimmed to the latest 500 lines.",
        ["log.debug_enabled"] = "Debug enabled: showing detailed HCI/ACL/ISO packets.",
        ["log.core_ready"] = "The audio core is running.", ["log.connected"] = "Connected.",
        ["log.disconnected"] = "Disconnected.", ["log.bluetooth_first"] = "Turn Bluetooth on first.",
        ["log.reconnect_wait"] = "Reconnecting: finishing a clean teardown before connecting again…",
        ["log.reconnecting"] = "Trying to restore the connection…",
        ["log.reconnect_stopped"] = "Automatic reconnection has stopped.",
        ["metrics.signal"] = "Signal: {0}", ["metrics.loss"] = "Lost packets (60 s): {0} ({1})",
        ["metrics.radio_events"] = "Radio error events (60 s): {0}", ["metrics.radio_unknown"] = "Radio errors: unavailable",
        ["metrics.stable"] = "Radio: no reported errors", ["metrics.unstable"] = "Connection: unstable",
        ["metrics.fair"] = "Connection: fair", ["metrics.waiting"] = "Connection: waiting for data", ["metrics.reconnecting"] = "Connection: reconnecting…",
        ["metrics.uptime"] = "Connected: {0}",
        ["metrics.battery"] = "Headphone battery",
        ["metrics.battery_part"] = "Headphone battery {0} of {1}",
        ["environment.open_setup"] = "Open Setup",
        ["power.title"] = "Radio power",
        ["power.saving"] = "Setting this to its most economical value would cut the reserved radio time by about {0}%.",
        ["power.saving_named"] = "The most economical choice here is \u201c{0}\u201d. It would cut the reserved radio time by about {1}%.",
        ["power.already_cheapest"] = "This is already the most economical value; nothing here is being spent unnecessarily.",
        ["power.duty"] = "The stream currently reserves about {0}% of every second of air.",
        ["power.caveat"] = "An estimate of transmission time, worked out from the settings on this page. It is not a battery measurement: how long headphones last also depends on their amplifier and noise cancelling, which this program cannot see.",
        ["power.metrics_off"] = "Nothing is asked of the controller, so this costs nothing at all.",
        ["power.metrics_signal"] = "One extra command a second. Negligible next to the audio stream.",
        ["power.metrics_full"] = "One command per second per channel. Still small next to the audio stream, but it is not free - turn it off if you are not watching the numbers.",
        ["power.multipoint_on"] = "Saves power: after a few seconds of silence nothing is transmitted at all until sound returns.",
        ["power.multipoint_off"] = "Costs power: the stream is held open through silence, so both radios keep working with nothing to carry.",
        ["power.idle_link_on"] = "The headphones are allowed to sleep through control-channel wake-ups they have nothing to say in. This is the largest saving on their side that costs nothing in audio quality or latency.",
        ["power.idle_link_off"] = "The control link runs at its negotiated rate, so both radios wake for every interval whether or not there is anything to carry. Raising this is the largest saving available here.",
        ["power.battery_poll_on"] = "One small packet each way, at the interval set here. Negligible next to the audio stream, and it is the only thing this program asks the headphones unprompted.",
        ["power.battery_poll_off"] = "Nothing is asked; the level moves only when the headphones report it themselves.",
        ["power.link_timeout"] = "Costs nothing while the headphones are in range. It only decides how long silence is tolerated before the link is given up, and a link being given up is what makes a reconnect - which is far more expensive than the wait.",
        ["power.idle"] = "Stops transmitting after a long silence. Only applies when releasing for other devices is off, which reacts in seconds rather than minutes.",
        ["power.reconnect_interval"] = "Applies only while the headphones are out of range. A shorter interval means the adapter listens almost continuously, which reconnects sooner and draws more power while it waits.",
        ["power.reconnect_window"] = "How long that listening goes on before it gives up. A longer window costs nothing while connected.",
        ["power.monitor"] = "Opens a microphone on this PC. It adds nothing to the radio, so it costs the headphones nothing.",
        ["environment.heading"] = "Things standing in the way:",
        ["environment.problem"] = "PROBLEM",
        ["environment.warning"] = "WARNING",
        ["codec.refused"] = "The connected headphones did not offer this and will refuse it.",
        ["codec.doubtful"] = "The headphones did not list this; it may not be accepted.",
        ["log.reconnect_started"] = "Connection failed; reconnecting automatically.",
        ["log.yielded"] = "Silence: the headphones were released so another device can use them.",
        ["log.reclaiming"] = "Audio is back; taking the headphones again.",
        ["log.levels_on"] = "Band levels are shown again inside the playing line.",
        ["log.levels_off"] = "Band levels hidden. The playing line stays: frame count, channel levels, delivered counts and signal keep being written.",
        ["console.rate_every"] = "Every line",
        ["console.rate_1s"] = "Playing line: 1 s",
        ["console.rate_2s"] = "Playing line: 2 s",
        ["console.rate_5s"] = "Playing line: 5 s",
        ["console.rate_15s"] = "Playing line: 15 s",
        ["choice.device_any"] = "Whichever paired device is found",
        ["settings.explain"] = "About {0}",
        ["settings.title"] = "Settings", ["settings.subtitle"] = "Changes are saved automatically and survive a restart.",
        ["settings.reset"] = "Restore defaults", ["settings.reconnect"] = "Reconnect",
        ["settings.filter"] = "Show", ["settings.layout"] = "Layout",
        ["settings.filter.all"] = "All categories", ["settings.filter.audio"] = "Audio",
        ["settings.filter.connection"] = "Connection", ["settings.filter.application"] = "Application & diagnostics",
        ["settings.layout.columns"] = "Adaptive columns", ["settings.layout.list"] = "List",
        ["settings.layout.panels"] = "3 panels",
        ["settings.custom_on_edit"] = "Editing this value switches LC3 quality to Custom automatically.",
        ["settings.main_preset"] = "Main LC3 preset",
        ["settings.panel.quality"] = "Sound",
        ["settings.panel.quality.sub"] = "How the audio is encoded and how the radio carries it",
        ["settings.panel.connection"] = "Connection",
        ["settings.panel.connection.sub"] = "Which headphones, reconnecting, sharing them, and the headset microphone",
        ["settings.panel.application"] = "Playback and application",
        ["settings.panel.application.sub"] = "What is played and how, plus how the app behaves in Windows",
        ["settings.connected_hint"] = "The headphones are connected. Stream settings take effect after reconnecting.",
        ["settings.saved_now"] = "“{0}” saved and applied immediately.",
        ["settings.saved_scope"] = "“{0}” saved - {1}.",
        ["settings.applied_now"] = "applied now",
        ["settings.reconnect_required"] = "reconnect required",
        ["settings.startup_error"] = "Windows startup could not be changed: {0}",
        ["scope.immediately"] = "applies immediately", ["scope.reconnect"] = "applies after reconnecting the headphones",
        ["scope.adapter"] = "applies after restarting the adapter",
        ["section.playback"] = "Playback", ["section.codec"] = "LC3 codec",
        ["section.radio"] = "Radio transport", ["section.microphone"] = "Microphone",
        ["section.connection"] = "Connection", ["section.application"] = "Application",
        ["section.language"] = "Language",
        ["section.tuning"] = "Diagnostics", ["section.other"] = "Other settings",
        ["section.sharing"] = "Multipoint",
        ["section.playback.sub"] = "Overall profile, stereo mapping and output level",
        ["section.codec.sub"] = "Audio detail and data rate; editable in Custom mode",
        ["section.radio.sub"] = "Balance latency, range and resilience",
        ["section.microphone.sub"] = "Disabled by default to preserve music bandwidth",
        ["section.connection.sub"] = "Which headphones, and how hard to try",
        ["section.sharing.sub"] = "Share the headphones with a phone during silence. Requires headphones that support multipoint",
        ["section.application.sub"] = "Background operation and Windows startup",
        ["section.language.sub"] = "Built-in and custom interface translations",
        ["section.tuning.sub"] = "Advanced adapter and stream diagnostics",
        ["setting.preset"] = "Stream configuration", ["setting.audio_context"] = "Content mode", ["setting.audio_mode"] = "Audio mode",
        ["setting.swap_channels"] = "Swap left and right", ["setting.rate_hz"] = "Sample rate",
        ["setting.frame_ms"] = "Frame duration (ms)", ["setting.octets"] = "Bytes per audio frame",
        ["setting.phy"] = "Audio CIS PHY (custom mode)", ["setting.retransmissions"] = "Retransmissions",
        ["setting.max_latency_ms"] = "Transport latency limit (ms)",
        ["setting.presentation_delay_ms"] = "Presentation delay (ms)",
        ["setting.diagnostics"] = "ASE diagnostics", ["setting.device"] = "Preferred device",
        ["setting.gain"] = "Volume before encoding", ["setting.idle_timeout_min"] = "Sleep after silence (minutes)",
        ["setting.reconnect_enabled"] = "Automatic reconnection",
        ["setting.multipoint_yield_enabled"] = "Share with a phone",
        ["setting.link_metrics"] = "Link measurements",
        ["choice.metrics_off"] = "Off - nothing is measured",
        ["choice.metrics_signal"] = "Signal strength only",
        ["choice.metrics_full"] = "Signal and packet loss",
        ["slider.share_sooner"] = "share sooner",
        ["slider.hold_longer"] = "hold on longer",
        ["setting.reconnect_interval_s"] = "Retry interval (seconds)",
        ["setting.reconnect_window_min"] = "Keep trying for (minutes)",
        ["setting.startup_reconnect_enabled"] = "Connect after Windows startup",
        ["setting.command_style"] = "HCI command addressing", ["setting.microphone_mode"] = "Headset microphone",
        ["setting.playback_source"] = "Playback capture source",
        ["setting.microphone_quality"] = "Microphone quality", ["setting.microphone_target"] = "Microphone destination",
        ["setting.microphone_gain"] = "Headset microphone volume", ["setting.monitor_enabled"] = "Microphone monitoring",
        ["setting.monitor_source"] = "Monitored microphone", ["setting.monitor_mode"] = "Monitoring mode",
        ["setting.monitor_gain"] = "Monitoring volume",
        ["setting.run_in_background"] = "Run in background", ["setting.start_with_windows"] = "Start with Windows",
        ["setting.language"] = "Language",
        ["setting.balance"] = "Left / right balance",
        ["desc.multipoint_yield_enabled"] = "Hand the audio endpoints back when the headphones say another device wants them, and take them again the moment it is done. The headphones announce this themselves, so nothing is released on a guess and nothing is released while this PC is the only thing playing. They stay connected throughout, so coming back rebuilds the stream rather than the connection, which takes about a second. Headphones that do not publish their availability never ask, and are never released.",
        ["desc.link_metrics"] = "How much this stack asks the controller while audio plays. Off asks nothing. Signal reads the strength of the connection. Full also asks the radio what it lost, which is the only honest source for the packet-loss figure. Every question is a message to the adapter, not over the air, so this costs the PC rather than the headphones.",
        ["setting.link_timeout_s"] = "Give up on the link after (seconds)",
        ["setting.battery_poll_min"] = "Ask for battery level every (minutes)",
        ["desc.balance"] = "Shifts the music towards one ear. 0 is even; -50 leaves only the left side, +50 only the right. It only ever turns the far side down, never boosts the near one, so it cannot distort.",
        ["desc.link_timeout_s"] = "Initial supervision timeout requested when connecting. The peer may subsequently request other valid connection parameters; the actual result is logged. This does not guarantee that audio channels survive the same duration.",
        ["desc.battery_poll_min"] = "Headphones are meant to report their level when it changes, and most do. This asks anyway, for the ones that stay silent. Each question is one small packet each way; 0 asks nothing and relies on what they send.",
        ["slider.left"] = "left", ["slider.right"] = "right",
        ["slider.drop_sooner"] = "notice a dead link sooner",
        ["slider.survive_range"] = "survive going out of range",
        ["slider.never_ask"] = "never ask", ["slider.rarely"] = "rarely",
        ["slider.untouched"] = "leave the link alone", ["slider.save_battery"] = "save their battery",
        ["setting.idle_link_latency"] = "Let the headphones sleep between control messages",
        ["desc.idle_link_latency"] = "Initial control link latency requested during audio setup. 0 leaves it unchanged. Peer parameter requests can subsequently change it. This is not an audio latency or range setting.",
        ["battery.refresh_tip"] = "Click to ask the headphones for their level now",
        ["log.battery_requested"] = "Asking the headphones for their battery level…",
        ["setup.restart_needed"] = "The driver binding has changed. Restart OpenLEAudio so the audio core opens the adapter again - until then it is still holding the old one.",
        ["setup.restart_now"] = "Restart now",
        ["settings.reconnecting"] = "Reconnecting the headphones. Settings that are baked into the stream take effect as soon as it comes back.",
        ["setting.media_controls_enabled"] = "Headphone media buttons",
        ["desc.media_controls_enabled"] = "Allow Play, Pause, Stop and track buttons to control the active Windows player through standard LE Media Control. Disconnecting never pauses the player. Headphone and player support are required.",
        ["desc.preset"] = "Automatic uses the supported AOSP LC3 playback profiles. Custom uses the same verified connection sequence with your requested values; hardware limits still apply.",
        ["desc.audio_context"] = "Music/Media uses Android's quality-first Media scenario. Gaming uses Android's low-latency Game priority list and announces the standard Game context to the headphones.",
        ["desc.audio_mode"] = "Stereo validates both channels; mono explicitly mixes left and right.",
        ["desc.swap_channels"] = "Swap the channels if the headphones play the sides in reverse.",
        ["desc.rate_hz"] = "Sample rate used by the Custom preset (16–48 kHz).",
        ["desc.frame_ms"] = "Frame duration used by the Custom preset (7.5 or 10 ms).",
        ["desc.octets"] = "How many bytes LC3 is given for each frame of audio. More bytes means a higher bitrate and more detail, and costs proportionally more air time and battery.",
        ["desc.phy"] = "2M uses less airtime. 1M may improve range, but needs more airtime; both endpoints must accept the complete configuration.",
        ["desc.retransmissions"] = "How many times the radio may repeat a packet.",
        ["desc.max_latency_ms"] = "The longest a frame may spend getting from this PC to the headphones, including retries. A higher limit gives the radio more room to repeat a lost packet; a lower one keeps audio closer to picture.",
        ["desc.presentation_delay_ms"] = "How long the headphones hold a frame before playing it. This is the buffer that absorbs an occasional late packet: too little crackles, too much is heard as lip-sync drift. The headphones publish the range they accept and their answer wins.",
        ["desc.diagnostics"] = "Read each stream state after the audio channels are established.",
        ["desc.device"] = "The headphones to reconnect automatically.",
        ["desc.gain"] = "Gain before LC3 encoding; 0 is silent, 1 is unchanged and 2 is boost.",
        ["desc.idle_timeout_min"] = "Release the audio endpoints and ISO channels after sustained silence while keeping the Bluetooth link. Playback must rebuild the stream when it resumes; 0 disables automatic release.",
        ["desc.reconnect_enabled"] = "Retry after the entire Bluetooth connection is lost. Audio recovery on a retained connection has its own settings.",
        ["desc.reconnect_interval_s"] = "Pause between full Bluetooth connection attempts. Scanning and establishing a connection take additional time.",
        ["desc.reconnect_window_min"] = "How long to retry; 0 means no time limit.",
        ["desc.startup_reconnect_enabled"] = "After an automatic background launch, look for remembered headphones every five seconds for three minutes.",
        ["desc.command_style"] = "How HCI commands are addressed over USB.",
        ["desc.playback_source"] = "The Windows capture endpoint sent to the headphones as music.",
        ["desc.microphone_mode"] = "Receive audio from the headset microphone over its Source ASE.",
        ["desc.microphone_quality"] = "LC3 voice quality; higher rates use more of the shared radio budget.",
        ["desc.microphone_target"] = "VB-CABLE writes to CABLE Input, which recording apps receive from CABLE Output.",
        ["desc.microphone_gain"] = "Gain applied to the headset microphone before publishing it to Windows.",
        ["desc.monitor_enabled"] = "Open the selected microphone and send it to the headphones.",
        ["desc.monitor_source"] = "Any active Windows microphone; the headset source appears when its LE microphone is enabled.",
        ["desc.monitor_mode"] = "Mix monitoring with captured music, or hear the microphone instead of music.",
        ["desc.monitor_gain"] = "Gain applied only to the monitored signal.",
        ["desc.run_in_background"] = "Closing the window keeps audio running and hides the app in the notification area.",
        ["desc.start_with_windows"] = "Launch the client in the background after signing in.",
        ["desc.language"] = "The interface language. Custom JSON language packs can be imported below.",
        ["trade.preset"] = "A preset fills the values below; Custom unlocks them.",
        ["trade.audio_context"] = "Gaming reduces buffering; Music/Media gives LC3 more time for detail and resilience.",
        ["trade.octets"] = "More octets improve bass and detail but require a higher data rate.",
        ["trade.retransmissions"] = "More retries reduce dropouts but may increase latency.",
        ["trade.max_latency_ms"] = "Lower reacts faster; higher tolerates interference better.",
        ["trade.presentation_delay_ms"] = "A buffer for synchronized playback in both ears.",
        ["trade.gain"] = "1.00 is unchanged; 1.05–2.00 boosts audio and the limiter prevents overflow.",
        ["trade.reconnect_interval_s"] = "Short retries more often; long is gentler on the adapter.",
        ["trade.reconnect_window_min"] = "0 keeps trying without a time limit.",
        ["trade.startup_reconnect_enabled"] = "Enabled by default; it stops as soon as the headphones connect or the three-minute window ends.",
        ["trade.idle_timeout_min"] = "0 disables sleeping the stream during silence.",
        ["trade.microphone_mode"] = "Off is the quality-first default: all capacity remains available for stereo music.",
        ["trade.microphone_quality"] = "Balanced is recommended for calls without spending the maximum airtime.",
        ["trade.microphone_target"] = "A separate VB-CABLE A/B cable avoids feeding the microphone back into music capture.",
        ["trade.microphone_gain"] = "1.00 is unchanged; boost carefully to avoid clipping.",
        ["trade.playback_source"] = "CABLE Output is the default music capture; this is separate from the preferred Bluetooth headset.",
        ["trade.monitor_enabled"] = "Off by default: no PC microphone is opened or monitored.",
        ["trade.monitor_source"] = "Changing the source never changes the music capture source.",
        ["trade.monitor_mode"] = "Mix keeps music audible; Replace mutes captured music while monitoring.",
        ["trade.monitor_gain"] = "1.00 is unchanged; boost carefully to avoid feedback or clipping.",
        ["trade.run_in_background"] = "Closing the window hides the client beside the clock.",
        ["trade.start_with_windows"] = "Starts hidden; open it from the notification-area icon.",
        ["choice.google"] = "Google/Android (recommended)", ["choice.windows"] = "Windows-like (recommended)", ["choice.high_quality"] = "Highest quality",
        ["choice.low_latency"] = "Low latency", ["choice.robust"] = "Resilient connection",
        ["choice.custom"] = "Custom", ["choice.context_media"] = "Music / Media", ["choice.context_game"] = "Gaming / low latency", ["choice.stereo"] = "Stereo (recommended)",
        ["choice.legacy"] = "Compatibility mode", ["choice.mono"] = "Mono",
        ["choice.mic_off"] = "Off - maximum playback quality", ["choice.mic_on"] = "On - receive headset microphone",
        ["choice.mic_voice"] = "Voice - 16 kHz", ["choice.mic_balanced"] = "Balanced - 32 kHz",
        ["choice.mic_high"] = "High - up to 48 kHz", ["choice.mic_vb_cable"] = "VB-CABLE Output for apps",
        ["choice.mic_vb_cable_a"] = "VB-CABLE A Output for apps", ["choice.mic_vb_cable_b"] = "VB-CABLE B Output for apps",
        ["choice.mic_no_target"] = "No virtual-cable output",
        ["choice.monitor_mix"] = "Mix with captured audio", ["choice.monitor_replace"] = "Replace captured audio",
        ["choice.class_device"] = "Bluetooth specification", ["choice.windows_command"] = "Windows-like",
        ["choice.class_interface"] = "Compatibility interface mode",
        ["slider.economical"] = "economical", ["slider.detail"] = "more detail",
        ["slider.faster"] = "faster", ["slider.resilient"] = "more resilient",
        ["slider.lower_latency"] = "lower latency", ["slider.more_headroom"] = "more headroom",
        ["slider.stable"] = "more stable", ["slider.silent"] = "0 · silent",
        ["slider.boost"] = "2 · boost", ["slider.default"] = "1.00 · default",
        ["slider.never"] = "never", ["slider.longer"] = "longer",
        ["slider.often"] = "more often", ["slider.gentle"] = "gentler",
        ["slider.unlimited"] = "unlimited", ["slider.limited"] = "limited time",
        ["language.english"] = "English", ["language.czech"] = "Čeština",
        ["language.title"] = "Language",
        ["language.subtitle"] = "Choose the interface language or manage custom translations.",
        ["language.import"] = "Import language…", ["language.export"] = "Export translation template…",
        ["language.json"] = "OpenLEAudio language pack", ["language.imported"] = "Language pack “{0}” imported.",
        ["language.import_error"] = "The language pack could not be imported: {0}",
        ["language.exported"] = "Translation template exported.",
        ["tray.open"] = "Open OpenLEAudio", ["tray.exit"] = "Exit",
        ["about.subtitle"] = "An open, configurable Bluetooth LE Audio client",
        ["about.how_title"] = "How it works",
        ["about.how_body"] = "The client captures stereo audio from the selected Windows output, splits it into left and right channels, encodes each with LC3 and sends timed ISO packets directly to the Bluetooth controller. GATT/ASCS signalling first discovers the headset capabilities, configures the codec and QoS, and only then starts streaming.",
        ["about.flow"] = "Windows audio → stereo capture → LC3 L/R → ISO SDU → CIS → headphones",
        ["about.ase_title"] = "ASE and CIS",
        ["about.ase_body1"] = "An ASE is an audio endpoint exposed by the headphones through ASCS. For stereo we normally configure two Sink ASEs: Front Left and Front Right. Both requests are sent atomically, like Windows, so both ears start in sync.",
        ["about.ase_body2"] = "Each active ASE maps to a CIS in one CIG. A CIS carries a separate LC3 stream for its ear. If a device supports stereo in one stream, the client can use one CIS with both channels; the plan always follows the discovered PACS/ASE capabilities.",
        ["about.windows_title"] = "Google LC3 and Android's configuration order",
        ["about.windows_body1"] = "Audio is encoded by liblc3, Google's reference LC3 implementation - the same codec Android ships and the one every LE Audio headset on the market is tested against. The stream configuration is chosen the way Android chooses it: an ordered list is walked and the first entry the headphones accept is used, starting with the 48 kHz 10 ms setting a phone asks for first. Version 1 asked for the configuration captured from the Windows driver instead, which is a different setting five places further down that list.",
        ["about.windows_body2"] = "The ASCS operations this sends match Android's byte for byte, which is checked by tests rather than assumed. Unlike the system driver, LC3 bitrate, frame duration, PHY, retransmissions, latency and presentation delay remain configurable: Custom unlocks them, and every value is still checked against what the headphones published before anything is sent.",
        ["about.mapping_title"] = "Discovery, GATT and capability mapping",
        ["about.mapping_body1"] = "Discovery finds LE advertisements and known bonds. After encryption, the GATT client reads PACS codec records, audio locations and supported contexts, then discovers ASCS control points and ASE endpoints. OpenLEAudio maps those declared capabilities to a valid LC3 configuration instead of assuming that every headset supports every preset.",
        ["about.mapping_body2"] = "The mapping is explicit: Windows capture endpoint → PCM stereo → channel allocation → LC3 frames → ISO SDUs → one or two CIS links. Optional Source ASE audio can return the headset microphone to a separate virtual cable.",
        ["about.stack_title"] = "A user-mode stack with safety boundaries",
        ["about.stack_body1"] = "The dedicated adapter is bound per device to Microsoft's WinUSB driver. The OpenLEAudio user-mode stack owns HCI, ACL/L2CAP, ATT/GATT, SMP pairing, BAP signalling and ISO transport while other adapters can stay under Windows. No custom kernel code is loaded.",
        ["about.stack_body2"] = "Vendor-specific HCI commands are blocked, GATT writes are limited to handles found during discovery, packet lengths are validated and output passes through a limiter. The original adapter and VB-CABLE state can be restored from Setup.",
        ["about.credits_body"] = "Design, implementation, testing and debugging of OpenLEAudio.\n\nMade by FajkPes, Claude Code and Chat GPT Codex. Enjoy!",
        ["setup.title"] = "Initial setup",
        ["setup.subtitle"] = "Prepare the driver, choose the Bluetooth adapter and configure the virtual audio cable.",
        ["setup.sign_title"] = "Sign the driver", ["setup.sign_button"] = "Sign driver",
        ["setup.sign_body"] = "Create a temporary local certificate and sign the WinUSB driver package before the first installation. Renew the signature every two years.",
        ["setup.sign_note"] = "The signing script removes the private signing key after installation. Secure Boot stays enabled because Windows loads Microsoft's WinUSB.sys.",
        ["setup.adapter_title"] = "Choose and verify the Bluetooth adapter",
        ["setup.adapter_body"] = "Select the dedicated USB adapter that OpenLEAudio may take over. Detection uses the hardware IDs from the signed driver package and works on both the Windows Bluetooth driver and WinUSB.",
        ["setup.detect_again"] = "Detect again", ["setup.detecting"] = "Detecting Bluetooth adapters…",
        ["setup.none_selected"] = "No adapter selected.", ["setup.none"] = "No present USB Bluetooth adapter was found.",
        ["setup.bind"] = "Switch to our stack", ["setup.restore"] = "Restore Windows driver", ["setup.status"] = "Driver status",
        ["setup.adapter_note"] = "LE is checked from the controller generation and Windows device data. Final LE Audio compatibility is confirmed safely after switching by reading the controller's LE feature set and the headset's GATT PACS/ASCS services; unsupported codec or channel configurations are rejected before streaming.",
        ["setup.vb_title"] = "Install and configure VB-CABLE",
        ["setup.vb_body"] = "Install VB-Audio Virtual Cable, then let OpenLEAudio set it to 48 kHz / 16-bit and use it as the Windows playback route. The original audio settings are backed up for restoration.",
        ["setup.vb_download"] = "VB-CABLE website", ["setup.vb_install"] = "Install VB-CABLE", ["setup.vb_setup"] = "Configure VB-CABLE",
        ["setup.vb_check"] = "Check VB-CABLE", ["setup.vb_restore"] = "Restore VB-CABLE",
        ["setup.stack_ours"] = "OpenLEAudio / WinUSB stack", ["setup.stack_windows"] = "Windows Bluetooth stack",
        ["setup.adapter_detail"] = "{0}\nHardware ID: {1}\nDriver: {2}\nCurrent binding: {3}\nDriver package: {4}",
        ["setup.supported"] = "supported; LE Audio controller features are verified after switching",
        ["setup.unsupported"] = "this adapter is not in the driver package yet, so switching is disabled. Run “ADD Bluetooth adapter.bat” in the release folder: it reads the id from Windows, adds it and signs the package again.",
        ["setup.not_listed"] = "not in the driver package",
        ["setup.detect_error"] = "Adapter detection failed: {0}", ["setup.files_missing"] = "The project setup scripts could not be found.",
        ["setup.choose_adapter"] = "Choose an adapter first.", ["setup.started"] = "The setup tool opened in a separate PowerShell window.",
        ["setup.restart_title"] = "Restart the app",
        ["setup.restart_body"] = "Use Restart now after changing the driver. The app will close its audio core before starting a fresh instance. The new process will open the selected WinUSB adapter and verify its Bluetooth 5.2+ LE Isochronous Channels support before scanning for LE Audio devices.",
    };

    private static readonly Dictionary<string, string> Cs = new()
    {
        ["section.recovery"] = "Obnova zvuku",
        ["section.recovery.sub"] = "Návrat zvuku při zachovaném Bluetooth spojení",
        ["setting.audio_recovery_enabled"] = "Automaticky obnovovat zvuk",
        ["setting.audio_recovery_interval_s"] = "Prodleva mezi pokusy o obnovu zvuku (sekundy)",
        ["setting.audio_recovery_window_min"] = "Časový limit obnovy zvuku (minuty)",
        ["desc.audio_recovery_enabled"] = "Při zániku audio kanálu jej znovu vytvoří bez úmyslného odpojení Bluetooth. Pouhá ztráta paketů obnovu kanálu nevyžaduje. Nezávislé na opětovném připojení celého Bluetooth.",
        ["desc.audio_recovery_interval_s"] = "Prodleva po výpadku audia nebo neúspěšné obnově. Samotné vytvoření kanálů zabere další čas. Změna platí i během čekání.",
        ["desc.audio_recovery_window_min"] = "0 znamená bez časového omezení, dokud obnovu nezastavíš nebo nezanikne Bluetooth spojení. Při převzetí jiným zdrojem program čeká. Konečný limit zastaví obnovu zvuku, ale úmyslně neodpojí Bluetooth.",
        ["setting.acl_phy"] = "Preference PHY řídicího spojení",
        ["choice.acl_auto"] = "Automaticky (1M nebo 2M)",
        ["desc.acl_phy"] = "Nezávislé na PHY audio kanálů CIS. Automaticky dovolí adaptéru vyjednat 1M nebo 2M; nejde o přepínání podle síly signálu. Preference není záruka. Vyjednaný výsledek se zapisuje do logu.",
        ["log.audio_recovery"] = "Zvuk přerušen: čekám na obnovu audio kanálů, Bluetooth spojení zůstává.",
        ["log.audio_recovery_stopped"] = "Obnovu zvuku zastavilo nastavení nebo časový limit. Pro návrat zvuku sluchátka ručně odpoj a připoj.",

        ["device.info_custom"] = "Custom: vybraná hodnota | rozsah programu (limity sluchátek níže)",
        ["device.info_qos_note"] = "PAC řádky určují možné kombinace kodeku. QoS limity nahoře platí jen pro uvedený naposledy vyjednaný kodek a PHY. Preference RTN a PHY nejsou úplným seznamem podpory. Neznámé kombinace musí ověřit sluchátka a řadič při vyjednání.",
        ["radio.explanation"] = "Čtení standardním HCI. Absolutní TX výkon spojení řídí řadič/firmware; univerzální HCI posuvník neexistuje. Rozsah adaptéru není aktuální výkon spojení. Nedostupný údaj neznamená 0 dBm.",
        ["radio.unknown"] = "nedostupné",
        ["radio.tx"] = "Vysílací výkon PC",
        ["radio.link_max"] = "Maximum spojení",
        ["radio.range"] = "Rozsah adaptéru",
        ["preflight.invalid"] = "Nastavení odmítnuto před reconnectem",

        ["device.star_hint"] = "Hvězdička: připojovat bez potvrzení, i po výpadku",
        ["device.confirm_title"] = "Povolit připojení?",
        ["device.confirm_body"] = "Zařízení nemá hvězdičku. Potvrď toto připojení; podle potřeby proběhne párování.",
        ["device.cancel"] = "Zrušit",
        ["device.info_title"] = "Schopnosti zařízení",
        ["device.info_current"] = "Potvrzená konfigurace přenosu",
        ["device.info_supported"] = "LC3 možnosti hlášené zařízením (jeden záznam na řádek)",
        ["device.info_help"] = "V Nastavení zvol Vlastní. Frekvenci, délku rámce a bajty vybírej ze stejného řádku; kombinace napříč řádky nemusí fungovat. Bitrate (kb/s na kanál) = bajty × 8 / rámec (ms). Transportní latence je horní limit; prezentační zpoždění omezují oba ASE po vyjednání kodeku. Nejnižší latence není zaručena při každém bitratu a kvalitě signálu.",

        ["nav.setup"]="Příprava", ["nav.devices"]="Zařízení", ["nav.settings"]="Nastavení", ["nav.language"]="Jazyk", ["nav.about"]="O aplikaci",
        ["devices.title"]="Bluetooth a zařízení", ["status.starting"]="Spouštím…", ["devices.bluetooth"]="Bluetooth",
        ["devices.scan_again"]="Hledat znovu", ["devices.paired"]="Spárovaná zařízení", ["devices.found"]="Nalezená zařízení",
        ["devices.unpair"]="Odpárovat", ["common.on"]="Zapnuto", ["common.off"]="Vypnuto",
        ["common.success"]="Hotovo", ["common.error"]="Něco se nepodařilo",
        ["log.title"]="Průběh", ["log.debug_on"]="Debug zapnutý", ["log.debug_off"]="Debug vypnutý",
        ["log.follow_on"]="Sledování zapnuto", ["log.follow_off"]="Sledování vypnuto", ["log.down"]="↓ Dolů",
        ["log.copy"]="Kopírovat vše", ["log.clear"]="Vymazat",
        ["log.debug_tip"]="Podrobné HCI/ACL/ISO pakety; vypnutí podrobný log vyčistí",
        ["log.down_tip"]="Skočit na konec a znovu sledovat nové záznamy",
        ["log.debug_disabled"]="Debug vypnutý. Podrobnosti o paketech skončily; konzole si historii nechává, zkrácenou na posledních 500 řádků.",
        ["log.debug_enabled"]="Debug zapnut: zobrazuji podrobné HCI/ACL/ISO pakety.",
        ["log.core_ready"]="Jádro běží.", ["log.connected"]="Připojeno.", ["log.disconnected"]="Odpojeno.",
        ["log.bluetooth_first"]="Nejdřív zapni Bluetooth.", ["log.reconnect_wait"]="Přepojuji: dokončuji čisté uvolnění kanálů a hned se připojím znovu…",
        ["log.reconnecting"]="Zkouším obnovit spojení…", ["log.reconnect_stopped"]="Automatické obnovení spojení skončilo.",
        ["settings.title"]="Nastavení", ["settings.subtitle"]="Hodnoty se ukládají samy a přežijí restart.",
        ["settings.reset"]="Obnovit výchozí nastavení", ["about.subtitle"]="Otevřený a konfigurovatelný klient pro Bluetooth LE Audio",
        ["settings.filter"]="Zobrazit", ["settings.layout"]="Rozložení",
        ["settings.filter.all"]="Všechny kategorie", ["settings.filter.audio"]="Zvuk",
        ["settings.filter.connection"]="Připojení", ["settings.filter.application"]="Aplikace a diagnostika",
        ["settings.layout.columns"]="Adaptivní sloupce", ["settings.layout.list"]="Seznam pod sebou",
        ["settings.layout.panels"]="3 panely",
        ["settings.custom_on_edit"]="Úprava této hodnoty automaticky přepne kvalitu LC3 na Vlastní.",
        ["settings.main_preset"]="Hlavní LC3 preset",
        ["settings.panel.quality"]="Zvuk",
        ["settings.panel.quality.sub"]="Jak se zvuk kóduje a jak ho nese rádio",
        ["settings.panel.connection"]="Připojení",
        ["settings.panel.connection.sub"]="Která sluchátka, opětovné připojení, sdílení a mikrofon",
        ["settings.panel.application"]="Přehrávání a aplikace",
        ["settings.panel.application.sub"]="Co a jak se přehrává, a jak se aplikace chová ve Windows",
        ["tray.open"]="Otevřít OpenLEAudio", ["tray.exit"]="Ukončit",
        ["about.how_title"]="Jak program funguje",
        ["about.how_body"]="Klient zachytí stereo zvuk z vybraného výstupu Windows, rozdělí jej na levý a pravý kanál, každý zakóduje pomocí LC3 a předá přímo Bluetooth řadiči jako časované ISO pakety. Signalizace přes GATT/ASCS nejdříve zjistí schopnosti sluchátek, nastaví kodek a QoS a teprve poté spustí stream.",
        ["about.mapping_title"]="Discovery, GATT a mapování schopností",
        ["about.mapping_body1"]="Discovery najde LE reklamy a známá spárování. Po zašifrování GATT klient načte z PACS záznamy kodeku, umístění zvuku a podporované kontexty a poté najde řídicí body ASCS a koncové body ASE. OpenLEAudio mapuje deklarované schopnosti na platnou konfiguraci LC3 a nepředpokládá, že každá sluchátka umí každý preset.",
        ["about.mapping_body2"]="Mapování je explicitní: záznamový endpoint Windows → PCM stereo → přiřazení kanálů → LC3 rámce → ISO SDU → jeden nebo dva CIS spoje. Volitelný zvuk Source ASE může vrátit mikrofon sluchátek do samostatného virtuálního kabelu.",
        ["about.stack_title"]="User-mode stack s bezpečnostními hranicemi",
        ["about.stack_body1"]="Vyhrazený adaptér je po jednotlivém zařízení napojen na WinUSB driver Microsoftu. User-mode stack OpenLEAudio obsluhuje HCI, ACL/L2CAP, ATT/GATT, SMP párování, BAP signalizaci a ISO přenos, zatímco jiné adaptéry mohou zůstat pod Windows. Nenačítá se žádný vlastní kód do kernelu.",
        ["about.stack_body2"]="Vendor-specific HCI příkazy jsou blokované, GATT zápisy jsou omezené na handly nalezené při discovery, délky paketů se ověřují a výstup prochází limiterem. Původní stav adaptéru i VB-CABLE lze obnovit v Přípravě.",
        ["about.flow"]="Zvuk Windows → stereo capture → LC3 L/R → ISO SDU → CIS → sluchátka",
        ["about.ase_title"]="ASE a CIS",
        ["about.ase_body1"]="ASE je koncový bod zvuku, který sluchátka vystaví přes ASCS. Pro stereo obvykle nakonfigurujeme dva Sink ASE: levý s umístěním Front Left a pravý s Front Right. Oba požadavky odesíláme společně, stejně jako Windows, aby se uši spustila synchronně.",
        ["about.ase_body2"]="Každý aktivní ASE se mapuje na CIS v jedné CIG. CIS nese samostatný tok LC3 pro příslušné ucho. Pokud zařízení podporuje stereo v jednom toku, klient umí zvolit i jediný CIS s oběma kanály; konfigurace se vždy přizpůsobí nalezeným PACS/ASE schopnostem.",
        ["about.windows_title"]="Googlí LC3 a Androidí pořadí konfigurací",
        ["about.windows_body1"]="Zvuk kóduje liblc3, referenční implementace LC3 od Googlu - tentýž kodek, který má Android, a ten, proti kterému jsou testována všechna LE Audio sluchátka na trhu. Konfigurace streamu se vybírá tak, jak ji vybírá Android: projde se seřazený seznam a použije se první položka, kterou sluchátka přijmou, počínaje nastavením 48 kHz / 10 ms, o které telefon žádá jako o první. Verze 1 místo toho žádala o konfiguraci odečtenou z Windows driveru, což je jiné nastavení o pět míst níž.",
        ["about.windows_body2"]="ASCS operace, které odsud odcházejí, se s Androidem shodují bajt po bajtu - hlídají to testy, není to domněnka. Na rozdíl od systémového ovladače zůstává nastavitelný bitrate LC3, délka rámce, PHY, počet opakování, latence i prezentační zpoždění: odemkne je Vlastní, a každá hodnota se před odesláním pořád ověřuje proti tomu, co sluchátka zveřejnila.",
        ["about.credits_body"]="Návrh, implementace, testování a ladění OpenLEAudio.\n\nMade by FajkPes, Claude Code and Chat GPT Codex. Enjoy!",
        ["status.unavailable"]="Nedostupné", ["status.core_failed"]="Jádro se nepodařilo spustit",
        ["status.core_unavailable"]="Jádro není dostupné", ["status.turning_on"]="Zapínám…",
        ["status.turning_off"]="Vypínám…", ["status.scanning"]="Hledám zařízení…", ["status.off"]="Vypnuto",
        ["status.adapter_off"]="Adaptér je vypnutý", ["status.none_found"]="Nic nového v okolí",
        ["status.scan_failed"]="Hledání selhalo", ["common.saved"]="uloženo",
        ["status.found"]="Nalezeno: {0}", ["settings.startup_error"]="Spuštění s Windows se nepodařilo nastavit: {0}",
        ["device.connecting"]="Připojuji…", ["device.connected_playing"]="Připojeno, hraje",
        ["device.connected"]="Připojeno", ["device.paired"]="Spárováno", ["device.playing"]="Hraje",
        ["device.disconnect"]="Odpojit", ["device.connect"]="Připojit", ["device.pair"]="Spárovat",
        ["log.copied"]="Zkopírováno", ["settings.reconnect"]="Znovu připojit",
        ["metrics.signal"]="Signál: {0}", ["metrics.loss"]="Ztracené pakety (60 s): {0} ({1})",
        ["metrics.radio_events"]="Chybové události rádia (60 s): {0}", ["metrics.radio_unknown"]="Chyby rádia: údaj není dostupný",
        ["metrics.stable"]="Rádio: bez hlášených chyb", ["metrics.unstable"]="Spojení: nestabilní",
        ["metrics.fair"]="Spojení: přijatelné", ["metrics.waiting"]="Spojení: čekám na data", ["metrics.reconnecting"]="Spojení: obnovuji…",
        ["metrics.uptime"]="Připojeno: {0}",
        ["metrics.battery"]="Baterie sluchátek",
        ["metrics.battery_part"]="Baterie sluchátek {0} z {1}",
        ["environment.open_setup"]="Otevřít Setup",
        ["power.title"]="Spotřeba rádia",
        ["power.saving"]="Nastavení na nejúspornější hodnotu by zkrátilo rezervovaný vysílací čas zhruba o {0} %.",
        ["power.saving_named"]="Nejúspornější volba je tady \u201e{0}\u201c. Zkrátila by rezervovaný vysílací čas zhruba o {1} %.",
        ["power.already_cheapest"]="Tohle už je nejúspornější hodnota, nic se tu neplýtvá.",
        ["power.duty"]="Stream teď rezervuje asi {0} % každé sekundy na vysílání.",
        ["power.caveat"]="Odhad vysílacího času spočítaný z nastavení na této stránce. Není to měření baterie: výdrž sluchátek závisí i na zesilovači a potlačení hluku, na což tenhle program nevidí.",
        ["power.metrics_off"]="Řadiče se na nic neptáme, takže to nestojí vůbec nic.",
        ["power.metrics_signal"]="Jeden příkaz navíc za sekundu. Proti zvukovému streamu zanedbatelné.",
        ["power.metrics_full"]="Jeden příkaz za sekundu na každý kanál. Proti streamu pořád málo, ale zadarmo to není – když čísla nesleduješ, vypni to.",
        ["power.multipoint_on"]="Šetří energii: po pár sekundách ticha se nevysílá vůbec nic, dokud se zvuk nevrátí.",
        ["power.multipoint_off"]="Stojí energii: stream zůstává otevřený i přes ticho, takže obě rádia pracují a nemají co nést.",
        ["power.idle_link_on"]="Sluchátka smí prospat probuzení řídicího kanálu, ve kterých nemají co říct. Je to největší úspora na jejich straně, která nestojí nic na kvalitě ani latenci zvuku.",
        ["power.idle_link_off"]="Řídicí linka běží na dohodnuté frekvenci, takže se obě rádia budí každý interval, ať je co přenášet nebo ne. Zvýšení téhle hodnoty je největší dostupná úspora.",
        ["power.battery_poll_on"]="Jeden malý paket tam a zpět v nastaveném intervalu. Vedle audio streamu zanedbatelné, a je to jediná věc, na kterou se program sluchátek ptá sám od sebe.",
        ["power.battery_poll_off"]="Neptáme se na nic; hodnota se pohne, jen když ji sluchátka nahlásí sama.",
        ["power.link_timeout"]="Dokud jsou sluchátka v dosahu, nestojí to nic. Rozhoduje jen o tom, jak dlouho se toleruje ticho, než se spojení vzdá - a vzdané spojení znamená nové připojení, které je mnohem dražší než to čekání.",
        ["power.idle"]="Po delším tichu přestane vysílat. Uplatní se jen když je uvolňování pro jiná zařízení vypnuté – to reaguje v sekundách, ne v minutách.",
        ["power.reconnect_interval"]="Týká se jen doby, kdy jsou sluchátka mimo dosah. Kratší interval znamená, že adaptér poslouchá skoro nepřetržitě: připojí se dřív a mezitím víc odebírá.",
        ["power.reconnect_window"]="Jak dlouho tohle poslouchání trvá, než to vzdá. Při připojených sluchátkách nestojí nic.",
        ["power.monitor"]="Otevře mikrofon na tomhle PC. Rádia se to netýká, takže to sluchátka nic nestojí.",
        ["environment.heading"]="Co překáží:",
        ["environment.problem"]="PROBLÉM",
        ["environment.warning"]="VAROVÁNÍ",
        ["codec.refused"]="Připojená sluchátka tohle nenabídla a odmítnou to.",
        ["codec.doubtful"]="Sluchátka tuhle hodnotu neuvedla, nemusí ji přijmout.",
        ["log.reconnect_started"]="Připojení selhalo, zkouším to automaticky dál.",
        ["log.yielded"]="Ticho: sluchátka uvolněna, může si je vzít jiné zařízení.",
        ["log.reclaiming"]="Zvuk se vrátil, beru si sluchátka zpátky.",
        ["log.levels_on"]="Úrovně pásem se v řádku přehrávání zase vypisují.",
        ["log.levels_off"]="Úrovně pásem skryté. Řádek přehrávání zůstává: počet rámců, úrovně kanálů, odeslané pakety i síla signálu se píšou dál.",
        ["console.rate_every"]="Každý řádek",
        ["console.rate_1s"]="Řádek přehrávání: 1 s",
        ["console.rate_2s"]="Řádek přehrávání: 2 s",
        ["console.rate_5s"]="Řádek přehrávání: 5 s",
        ["console.rate_15s"]="Řádek přehrávání: 15 s",
        ["choice.device_any"]="Kterákoliv spárovaná sluchátka",
        ["settings.explain"]="K čemu je {0}",
        ["settings.connected_hint"]="Sluchátka jsou připojená. Nastavení streamu se projeví až po přepojení.",
        ["settings.saved_now"]="„{0}“ uloženo, projeví se hned.",
        ["settings.saved_scope"]="„{0}“ uloženo - {1}.",
        ["settings.applied_now"]="použito hned",
        ["settings.reconnect_required"]="nutné znovu připojit",
        ["scope.immediately"]="projeví se hned", ["scope.reconnect"]="projeví se po odpojení a připojení sluchátek",
        ["scope.adapter"]="projeví se po vypnutí a zapnutí adaptéru",
        ["section.playback"]="Přehrávání", ["section.codec"]="Kodek LC3", ["section.radio"]="Rádiový přenos",
        ["section.microphone"]="Mikrofon", ["section.connection"]="Připojení", ["section.application"]="Aplikace",
        ["section.language"]="Jazyk",
        ["section.tuning"]="Ladění", ["section.other"]="Další nastavení",
        ["section.sharing"]="Multipoint",
        ["section.playback.sub"]="Celkový profil, stereo a výstupní úroveň",
        ["section.codec.sub"]="Detail zvuku a datový tok; upravuje se v režimu Vlastní",
        ["section.radio.sub"]="Kompromis mezi odezvou, dosahem a odolností",
        ["section.microphone.sub"]="Ve výchozím stavu nebere kapacitu hudebnímu streamu",
        ["section.connection.sub"]="Která sluchátka a jak vytrvale je hledat",
        ["section.sharing.sub"]="Při tichu půjčit sluchátka telefonu. Vyžaduje sluchátka s podporou multipointu",
        ["section.application.sub"]="Jazyk, běh na pozadí a spuštění s Windows",
        ["section.language.sub"]="Vestavěné a vlastní překlady rozhraní",
        ["section.tuning.sub"]="Pokročilá diagnostika adaptéru a streamů",
        ["setting.preset"]="Konfigurace streamu", ["setting.audio_context"]="Režim obsahu", ["setting.audio_mode"]="Režim zvuku",
        ["setting.swap_channels"]="Prohodit levý a pravý", ["setting.rate_hz"]="Vzorkovací frekvence",
        ["setting.frame_ms"]="Délka rámce (ms)", ["setting.octets"]="Bajtů na rámec zvuku",
        ["setting.phy"]="PHY audio kanálů CIS (vlastní režim)", ["setting.retransmissions"]="Počet opakování",
        ["setting.max_latency_ms"]="Limit přenosové latence (ms)", ["setting.presentation_delay_ms"]="Vyrovnávací paměť ve sluchátkách (ms)",
        ["setting.diagnostics"]="Diagnostika ASE", ["setting.device"]="Preferované zařízení",
        ["setting.gain"]="Hlasitost před kódováním", ["setting.idle_timeout_min"]="Uspat po tichu (minuty)",
        ["setting.reconnect_enabled"]="Automatické připojení", ["setting.reconnect_interval_s"]="Interval pokusů (sekundy)",
        ["setting.multipoint_yield_enabled"]="Sdílet s telefonem",
        ["setting.link_metrics"]="Měření linky",
        ["choice.metrics_off"]="Vypnuto – nic se neměří",
        ["choice.metrics_signal"]="Jen síla signálu",
        ["choice.metrics_full"]="Signál i ztrátovost paketů",
        ["slider.share_sooner"]="půjčit dřív",
        ["slider.hold_longer"]="držet déle",
        ["setting.reconnect_window_min"]="Zkoušet po dobu (minuty)", ["setting.command_style"]="Adresování HCI příkazů",
        ["setting.startup_reconnect_enabled"]="Připojit po spuštění Windows",
        ["setting.playback_source"]="Zdroj přehrávaného zvuku",
        ["setting.microphone_mode"]="Mikrofon sluchátek", ["setting.microphone_quality"]="Kvalita mikrofonu",
        ["setting.microphone_target"]="Výstup mikrofonu sluchátek", ["setting.microphone_gain"]="Hlasitost mikrofonu sluchátek",
        ["setting.monitor_enabled"]="Odposlech mikrofonu", ["setting.monitor_source"]="Odposlouchávaný mikrofon",
        ["setting.monitor_mode"]="Režim odposlechu", ["setting.monitor_gain"]="Hlasitost odposlechu",
        ["setting.run_in_background"]="Běžet na pozadí",
        ["setting.start_with_windows"]="Spouštět s Windows", ["setting.language"]="Jazyk",
        ["setting.balance"]="Vyvážení levá / pravá",
        ["desc.multipoint_yield_enabled"]="Vrátí audio endpointy ve chvíli, kdy sluchátka řeknou, že je chce jiné zařízení, a vezme si je zpátky, jakmile skončí. Sluchátka to hlásí sama, takže se nic neuvolňuje na základě odhadu ani ve chvíli, kdy hraje jen tohle PC. Spojení zůstává celou dobu nahoře, takže návrat staví znovu jen stream, ne připojení - trvá to zhruba sekundu. Sluchátka, která svou dostupnost nezveřejňují, si nikdy neřeknou a nikdy se neuvolní.",
        ["desc.link_metrics"]="Kolik se toho tenhle stack během přehrávání ptá řadiče. Vypnuto se neptá na nic. Signál čte sílu spojení. Plné se navíc ptá rádia, co ztratilo - což je jediný poctivý zdroj údaje o ztrátovosti. Každý dotaz je zpráva do adaptéru, ne do éteru, takže to stojí PC, ne sluchátka.",
        ["setting.link_timeout_s"]="Považovat spojení za ztracené po (sekundách)",
        ["setting.battery_poll_min"]="Ptát se na stav baterie každých (minut)",
        ["desc.balance"]="Posune hudbu k jednomu uchu. 0 je vyrovnané, −50 nechá hrát jen levou stranu, +50 jen pravou. Vzdálenější stranu vždycky jen ztlumí, nikdy nezesílí tu bližší, takže nemůže zkreslit.",
        ["desc.link_timeout_s"]="Počáteční dohledový timeout požadovaný při připojení. Sluchátka mohou později vyžádat jiné platné parametry; skutečný výsledek se loguje. Nezaručuje, že audio kanály přežijí stejně dlouhou dobu.",
        ["desc.battery_poll_min"]="Sluchátka mají hlásit změnu stavu sama a většina to dělá. Tohle se zeptá i tak, kvůli těm, která mlčí. Každý dotaz je jeden malý paket tam a zpět; 0 se neptá vůbec a spoléhá na to, co pošlou.",
        ["slider.left"]="vlevo", ["slider.right"]="vpravo",
        ["slider.drop_sooner"]="poznat mrtvé spojení dřív",
        ["slider.survive_range"]="přežít odchod z dosahu",
        ["slider.never_ask"]="neptat se", ["slider.rarely"]="zřídka",
        ["slider.untouched"]="nechat linku být", ["slider.save_battery"]="šetřit jim baterku",
        ["setting.idle_link_latency"]="Nechat sluchátka spát mezi řídicími zprávami",
        ["desc.idle_link_latency"]="Počáteční požadavek na vynechávání událostí řídicí linky při nastavení audia. 0 ji nemění. Pozdější požadavek sluchátek může hodnotu změnit. Nejde o nastavení latence zvuku ani dosahu.",
        ["battery.refresh_tip"]="Klikni a sluchátek se hned zeptáme na stav baterie",
        ["log.battery_requested"]="Ptám se sluchátek na stav baterie…",
        ["setup.restart_needed"]="Přiřazení ovladače se změnilo. Restartuj OpenLEAudio, aby audio jádro adaptér otevřelo znovu - do té doby drží ten starý.",
        ["setup.restart_now"]="Restartovat teď",
        ["settings.reconnecting"]="Obnovuji spojení se sluchátky. Nastavení, která jsou součástí streamu, se projeví, jakmile se spojení vrátí.",
        ["setting.media_controls_enabled"]="Multimediální tlačítka sluchátek",
        ["desc.media_controls_enabled"]="Play, Pause, Stop a přeskakování skladeb ovládají aktivní přehrávač Windows přes standardní LE Media Control. Odpojení přehrávač nepozastavuje. Vyžaduje podporu ve sluchátkách i přehrávači.",
        ["desc.preset"]="Automatický režim vybírá podporované profily LC3 podle AOSP. Vlastní režim používá stejný ověřovaný postup s požadovanými hodnotami; limity hardwaru stále platí.",
        ["desc.audio_context"]="Hudba/Média používá Androidí kvalitativně orientovaný scénář Media. Herní režim používá Androidí seznam s nízkou latencí a sluchátkům oznámí standardní kontext Game.",
        ["desc.audio_mode"]="Stereo ověřuje oba kanály; mono výslovně smíchá levý a pravý kanál.",
        ["desc.swap_channels"]="Prohodí levý a pravý kanál, pokud sluchátka hrají strany obráceně.",
        ["desc.rate_hz"]="Vzorkovací frekvence pro preset Vlastní (16–48 kHz).",
        ["desc.frame_ms"]="Délka rámce pro preset Vlastní (7,5 nebo 10 ms).",
        ["desc.octets"]="Kolik bajtů dostane LC3 na jeden rámec zvuku. Víc bajtů znamená vyšší bitrate a víc detailu, a stojí úměrně víc vysílacího času a baterky.",
        ["desc.phy"]="2M šetří vysílací čas. 1M může zlepšit dosah, ale potřebuje více času; celou konfiguraci musí přijmout adaptér i sluchátka.",
        ["desc.retransmissions"]="Kolikrát smí rádio paket zopakovat.",
        ["desc.max_latency_ms"]="Maximální povolená přenosová latence linku.",
        ["desc.presentation_delay_ms"]="Jak dlouho sluchátka přijatý rámec podrží před přehráním.",
        ["desc.diagnostics"]="Po ustavení kanálů přečte stav každého streamu.",
        ["desc.device"]="Sluchátka, která se mají automaticky znovu připojit.",
        ["desc.gain"]="Zesílení před LC3 kodérem; 0 je ticho, 1 beze změny a 2 boost.",
        ["desc.idle_timeout_min"]="Po delším tichu uvolní audio endpointy a ISO kanály, ale ponechá Bluetooth spojení. Při pokračování se stream musí znovu vytvořit; 0 automatické uvolnění vypne.",
        ["desc.reconnect_enabled"]="Opakuje připojení po ztrátě celého Bluetooth spojení. Obnova zvuku přes zachované spojení má vlastní nastavení.",
        ["desc.reconnect_interval_s"]="Prodleva mezi pokusy o celé Bluetooth spojení. Hledání zařízení a navázání spojení zabere další čas.",
        ["desc.reconnect_window_min"]="Jak dlouho se má zkoušet; 0 znamená bez omezení.",
        ["desc.startup_reconnect_enabled"]="Po automatickém spuštění na pozadí tři minuty každých pět sekund hledá zapamatovaná sluchátka.",
        ["desc.command_style"]="Způsob adresování HCI příkazů po USB.",
        ["desc.playback_source"]="Zvukový vstup Windows, který se posílá do sluchátek jako hudba.",
        ["desc.microphone_mode"]="Přijímá zvuk z mikrofonu sluchátek přes jeho Source ASE.",
        ["desc.microphone_quality"]="Kvalita hlasového LC3; vyšší frekvence spotřebuje více společné rádiové kapacity.",
        ["desc.microphone_target"]="VB-CABLE zapisuje do CABLE Input, odkud jej nahrávací aplikace dostanou jako CABLE Output.",
        ["desc.microphone_gain"]="Zesílení mikrofonu sluchátek před odesláním do Windows.",
        ["desc.monitor_enabled"]="Otevře vybraný mikrofon a pošle jej do sluchátek.",
        ["desc.monitor_source"]="Libovolný aktivní mikrofon Windows; mikrofon sluchátek se ukáže po zapnutí jeho LE vstupu.",
        ["desc.monitor_mode"]="Přimíchá odposlech k hudbě, nebo jím hudbu nahradí.",
        ["desc.monitor_gain"]="Zesílení použité pouze pro odposlech.",
        ["desc.run_in_background"]="Zavření okna nechá zvuk běžet a aplikaci schová k hodinám.",
        ["desc.start_with_windows"]="Po přihlášení spustí klienta skrytě na pozadí.",
        ["desc.language"]="Jazyk rozhraní; vlastní JSON překlady lze importovat níže.",
        ["trade.preset"]="Preset vyplní hodnoty níže; Vlastní je odemkne.",
        ["trade.audio_context"]="Herní režim omezuje vyrovnávací prodlevu; Hudba/Média dává LC3 více prostoru pro detail a odolnost.",
        ["trade.octets"]="Více oktetů znamená lepší basy a detail, ale vyšší datový tok.",
        ["trade.retransmissions"]="Více opakování omezuje výpadky, může ale zvýšit odezvu.",
        ["trade.max_latency_ms"]="Nižší hodnota reaguje rychleji, vyšší lépe snáší rušení.",
        ["trade.presentation_delay_ms"]="Rezerva pro synchronní přehrání obou sluchátek.",
        ["trade.gain"]="1,00 je beze změny; 1,05–2,00 zesiluje a limiter zabrání přetečení.",
        ["trade.reconnect_interval_s"]="Krátce zkouší častěji; delší interval šetří adaptér.",
        ["trade.reconnect_window_min"]="0 znamená zkoušet bez časového omezení.",
        ["trade.startup_reconnect_enabled"]="Ve výchozím stavu zapnuto; skončí po připojení nebo po třech minutách.",
        ["trade.idle_timeout_min"]="0 vypne uspání streamu při tichu.",
        ["trade.microphone_mode"]="Vypnuto je výchozí: celá kapacita zůstane hudbě a stereo kvalitě.",
        ["trade.microphone_quality"]="Vyvážená je doporučená pro hovory bez maximální spotřeby vysílacího času.",
        ["trade.microphone_target"]="Samostatný VB-CABLE A/B zabrání návratu mikrofonu do stejného hudebního vstupu.",
        ["trade.microphone_gain"]="1,00 je beze změny; vyšší hodnoty mohou oříznout hlas.",
        ["trade.playback_source"]="CABLE Output je výchozí zdroj hudby a je oddělený od preferovaných Bluetooth sluchátek.",
        ["trade.monitor_enabled"]="Výchozí je vypnuto: aplikace neotevírá ani neodposlouchává žádný mikrofon z PC.",
        ["trade.monitor_source"]="Změna mikrofonu nikdy nezmění hlavní zdroj hudby.",
        ["trade.monitor_mode"]="Přimíchat ponechá hudbu; Nahradit ji během odposlechu ztlumí.",
        ["trade.monitor_gain"]="1,00 je beze změny; zesílení může způsobit vazbu nebo ořezání.",
        ["trade.run_in_background"]="Zavření okna aplikaci schová vedle hodin.",
        ["trade.start_with_windows"]="Spustí klienta skrytě; otevřete jej ikonou vedle hodin.",
        ["choice.google"]="Google/Android (doporučeno)", ["choice.windows"]="Jako Windows (doporučeno)", ["choice.high_quality"]="Nejvyšší kvalita",
        ["choice.low_latency"]="Nízká latence", ["choice.robust"]="Odolné spojení", ["choice.custom"]="Vlastní nastavení", ["choice.context_media"]="Hudba / Média", ["choice.context_game"]="Hraní / nízká latence",
        ["choice.stereo"]="Stereo (doporučeno)", ["choice.legacy"]="Kompatibilní režim", ["choice.mono"]="Mono",
        ["choice.mic_off"]="Vypnutý - maximum kvality", ["choice.mic_on"]="Zapnutý - přijímat mikrofon sluchátek",
        ["choice.mic_voice"]="Hlas - 16 kHz", ["choice.mic_balanced"]="Vyvážená - 32 kHz",
        ["choice.mic_high"]="Vysoká - až 48 kHz", ["choice.mic_vb_cable"]="VB-CABLE Output pro aplikace",
        ["choice.mic_vb_cable_a"]="VB-CABLE A Output pro aplikace", ["choice.mic_vb_cable_b"]="VB-CABLE B Output pro aplikace",
        ["choice.mic_no_target"]="Bez výstupu do virtuálního kabelu", ["choice.class_device"]="Dle Bluetooth specifikace",
        ["choice.monitor_mix"]="Přimíchat k zachycenému zvuku", ["choice.monitor_replace"]="Nahradit zachycený zvuk",
        ["choice.windows_command"]="Jako Windows", ["choice.class_interface"]="Kompatibilní interface režim",
        ["slider.economical"]="úspornější", ["slider.detail"]="více detailu", ["slider.faster"]="rychlejší",
        ["slider.resilient"]="odolnější", ["slider.lower_latency"]="nižší odezva", ["slider.more_headroom"]="větší rezerva",
        ["slider.stable"]="stabilnější", ["slider.silent"]="0 · ticho", ["slider.boost"]="2 · boost",
        ["slider.default"]="1,00 · výchozí", ["slider.never"]="nevypínat", ["slider.longer"]="delší čas",
        ["slider.often"]="častěji", ["slider.gentle"]="šetrněji", ["slider.unlimited"]="bez omezení",
        ["slider.limited"]="omezená doba", ["language.english"]="English", ["language.czech"]="Čeština",
        ["language.title"]="Jazyk", ["language.subtitle"]="Vyberte jazyk rozhraní nebo spravujte vlastní překlady.",
        ["language.import"]="Importovat jazyk…", ["language.export"]="Exportovat šablonu překladu…",
        ["language.json"]="Jazykový balíček OpenLEAudio", ["language.imported"]="Jazykový balíček „{0}“ byl importován.",
        ["language.import_error"]="Jazykový balíček se nepodařilo importovat: {0}",
        ["language.exported"]="Šablona překladu byla exportována.",
        ["setup.title"]="První nastavení", ["setup.subtitle"]="Připravte ovladač, vyberte Bluetooth adaptér a nastavte virtuální zvukový kabel.",
        ["setup.sign_title"]="Podepsat driver", ["setup.sign_button"]="Podepsat driver",
        ["setup.sign_body"]="Před první instalací vytvoří dočasný lokální certifikát a podepíše balíček ovladače WinUSB. Podpis obnovte každé dva roky.",
        ["setup.sign_note"]="Po instalaci skript soukromý podpisový klíč odstraní. Secure Boot zůstává zapnutý, protože Windows načítá vlastní WinUSB.sys od Microsoftu.",
        ["setup.adapter_title"]="Vybrat a ověřit Bluetooth adaptér", ["setup.adapter_body"]="Vyberte vyhrazený USB adaptér, který smí OpenLEAudio převzít. Detekce používá Hardware ID z podepsaného balíčku driveru a funguje s Bluetooth driverem Windows i s WinUSB.",
        ["setup.detect_again"]="Zjistit znovu", ["setup.detecting"]="Zjišťuji Bluetooth adaptéry…", ["setup.none_selected"]="Není vybraný adaptér.",
        ["setup.none"]="Nebyl nalezen žádný přítomný USB Bluetooth adaptér.", ["setup.bind"]="Přepnout na náš stack",
        ["setup.restore"]="Vrátit Windows driver", ["setup.status"]="Stav driveru",
        ["setup.adapter_note"]="LE se předběžně ověří podle generace řadiče a dat Windows. Konečná kompatibilita LE Audio se bezpečně potvrdí po přepnutí načtením LE funkcí řadiče a služeb GATT PACS/ASCS sluchátek; nepodporovaná konfigurace kodeku nebo kanálů je odmítnuta ještě před streamem.",
        ["setup.vb_title"]="Nainstalovat a nastavit VB-CABLE", ["setup.vb_body"]="Nainstalujte VB-Audio Virtual Cable a nechte OpenLEAudio nastavit 48 kHz / 16 bitů a trasu přehrávání Windows. Původní nastavení zvuku se zazálohuje pro obnovení.",
        ["setup.vb_download"]="Web VB-CABLE", ["setup.vb_install"]="Nainstalovat VB-CABLE", ["setup.vb_setup"]="Nastavit VB-CABLE", ["setup.vb_check"]="Zkontrolovat VB-CABLE", ["setup.vb_restore"]="Vrátit VB-CABLE",
        ["setup.stack_ours"]="OpenLEAudio / WinUSB stack", ["setup.stack_windows"]="Bluetooth stack Windows",
        ["setup.adapter_detail"]="{0}\nHardware ID: {1}\nDriver: {2}\nAktuální napojení: {3}\nBalíček driveru: {4}",
        ["setup.supported"]="podporováno; funkce řadiče pro LE Audio se ověří po přepnutí",
        ["setup.unsupported"]="tenhle adaptér zatím není v balíčku ovladače, takže přepnutí je zakázané. Spusť v release složce „ADD Bluetooth adapter.bat“: přečte ID z Windows, přidá ho a balíček znovu podepíše.",
        ["setup.not_listed"]="není v balíčku ovladače",
        ["setup.detect_error"]="Zjištění adaptérů selhalo: {0}",
        ["setup.files_missing"]="Instalační skripty projektu se nepodařilo najít.", ["setup.choose_adapter"]="Nejdřív vyberte adaptér.",
        ["setup.started"]="Nástroj nastavení se otevřel v samostatném okně PowerShellu.",
        ["setup.restart_title"]="Restartovat aplikaci",
        ["setup.restart_body"]="Po změně ovladače použijte Restartovat teď. Aplikace ukončí audio jádro a potom spustí novou instanci. Nový proces otevře vybraný WinUSB adaptér a před hledáním LE Audio zařízení ověří podporu Bluetooth 5.2+ LE Isochronous Channels.",
    };

    private static readonly Dictionary<string, Pack> Custom = new(StringComparer.OrdinalIgnoreCase);
    public static string CurrentCode { get; private set; } = "en";
    public static string DirectoryPath => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "OpenLEAudio", "Languages");

    static Loc() => ReloadCustomPacks();

    public static IEnumerable<(string Code, string Name)> Languages =>
        new[] { ("en", T("language.english", "English")), ("cs", T("language.czech", "Čeština")) }
            .Concat(Custom.Values.OrderBy(p => p.Name).Select(p => (p.Code, p.Name)));

    public static void SetLanguage(string? code) => CurrentCode = code == "cs" || (code is not null && Custom.ContainsKey(code)) ? code : "en";

    public static string T(string key, params object[] args)
    {
        string value;
        if (Custom.TryGetValue(CurrentCode, out var custom) && custom.Strings.TryGetValue(key, out var translated)) value = translated;
        else if (CurrentCode == "cs" && Cs.TryGetValue(key, out var czech)) value = czech;
        else value = En.TryGetValue(key, out var english) ? english : key;
        return args.Length == 0 ? value : string.Format(value, args);
    }

    public static void Apply(DependencyObject root)
    {
        TranslateOne(root);
        for (var i = 0; i < VisualTreeHelper.GetChildrenCount(root); i++) Apply(VisualTreeHelper.GetChild(root, i));
    }

    private static void TranslateOne(DependencyObject value)
    {
        if (value is TextBlock text) text.Text = TranslateLiteral(text.Text);
        if (value is ContentControl content && content.Content is string label) content.Content = TranslateLiteral(label);
        if (value is ToggleSwitch toggle)
        {
            if (toggle.OnContent is string on) toggle.OnContent = TranslateLiteral(on);
            if (toggle.OffContent is string off) toggle.OffContent = TranslateLiteral(off);
        }
        if (value is InfoBar info)
        {
            info.Title = TranslateLiteral(info.Title);
            info.Message = TranslateLiteral(info.Message);
        }
        if (ToolTipService.GetToolTip(value) is string tip) ToolTipService.SetToolTip(value, TranslateLiteral(tip));
    }

    private static string TranslateLiteral(string source)
    {
        var key = En.FirstOrDefault(x => x.Value == source).Key
            ?? Cs.FirstOrDefault(x => x.Value == source).Key
            ?? Custom.Values.SelectMany(pack => pack.Strings).FirstOrDefault(x => x.Value == source).Key;
        return key is null ? source : T(key);
    }

    public static string Import(string sourcePath)
    {
        var json = File.ReadAllText(sourcePath);
        var pack = JsonSerializer.Deserialize<Pack>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
            ?? throw new InvalidDataException("Empty language pack.");
        if (string.IsNullOrWhiteSpace(pack.Code) || string.IsNullOrWhiteSpace(pack.Name) || pack.Strings is null)
            throw new InvalidDataException("The pack needs code, name and strings fields.");
        if (pack.Code is "en" or "cs" || pack.Code.Any(c => !(char.IsLetterOrDigit(c) || c is '-' or '_')))
            throw new InvalidDataException("Use a unique language code containing letters, digits, '-' or '_'.");
        Directory.CreateDirectory(DirectoryPath);
        var target = Path.Combine(DirectoryPath, pack.Code + ".json");
        File.Copy(sourcePath, target, true);
        ReloadCustomPacks();
        return pack.Code;
    }

    public static void ExportTemplate(string path)
    {
        var pack = new Pack("my-language", "My language", new Dictionary<string, string>(En));
        File.WriteAllText(path, JsonSerializer.Serialize(pack, new JsonSerializerOptions { WriteIndented = true }));
    }

    private static void ReloadCustomPacks()
    {
        Custom.Clear();
        if (!Directory.Exists(DirectoryPath)) return;
        foreach (var path in Directory.EnumerateFiles(DirectoryPath, "*.json"))
        {
            try
            {
                var pack = JsonSerializer.Deserialize<Pack>(File.ReadAllText(path), new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                if (pack is not null && !string.IsNullOrWhiteSpace(pack.Code) && !string.IsNullOrWhiteSpace(pack.Name)) Custom[pack.Code] = pack;
            }
            catch { /* One broken community translation must not stop the app. */ }
        }
    }
}
